version: '3.8'
services:

  db:
    image: postgres:latest
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_PASSWORD: postgres
  app:
    build:
      context: ..
      dockerfile: .devcontainer/python-pg.Dockerfile

    volumes:
      - ../workspace:/mnt/workspace/
      - ../.ssh:/home/user/.ssh/

    command: sleep infinity
    network_mode: service:db

volumes:
  postgres-data: