version: '3.8'
services:
  app:
    build:
      context: ..
      dockerfile: .devcontainer/ubuntu-base.Dockerfile

    volumes:
      - ../workspace:/mnt/workspace/
      - ../.ssh:/home/user/.ssh/

    networks:
      - default

    command: sleep infinity